"""entradas: descuento y bruto

Revision ID: 8138c40abdaa
Revises: d4d60422032a
Create Date: 2025-08-25 11:48:43.664596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8138c40abdaa'
down_revision = 'd4d60422032a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_entrada_producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_bruto_sin_iva', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('descuento_porcentaje', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('descuento_importe', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_entrada_producto', schema=None) as batch_op:
        batch_op.drop_column('descuento_importe')
        batch_op.drop_column('descuento_porcentaje')
        batch_op.drop_column('precio_bruto_sin_iva')

    # ### end Alembic commands ###
