"""sync after RegistroEntradaProducto fix

Revision ID: d1cd0257ece7
Revises: 8138c40abdaa
Create Date: 2025-08-25 13:50:49.620641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1cd0257ece7'
down_revision = '8138c40abdaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_entrada_producto', schema=None) as batch_op:
        batch_op.drop_column('descuento_importe')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_entrada_producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descuento_importe', sa.NUMERIC(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###
