"""entrada: documento e importes

Revision ID: d4d60422032a
Revises: 77b93f325736
Create Date: 2025-08-25 11:12:10.950035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d60422032a'
down_revision = '77b93f325736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_entrada_producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_documento', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('numero_documento', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('precio_sin_iva', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('iva_porcentaje', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('precio_con_iva', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_entrada_producto', schema=None) as batch_op:
        batch_op.drop_column('precio_con_iva')
        batch_op.drop_column('iva_porcentaje')
        batch_op.drop_column('precio_sin_iva')
        batch_op.drop_column('numero_documento')
        batch_op.drop_column('tipo_documento')

    # ### end Alembic commands ###
